### PR TITLE
Reverse string java Program

### PR DESCRIPTION
**Pull request by Pandz18**

### CODE REVIEW

**Comment by LorenzNickel** [comment]
Hey @Pandz18,

thanks for your contribution.

Please try to keep your Pull Requests atomic in the future and only add one additional feature within one PR.

However, regarding this PR, it seems like you wanted to implement **BubbleSort** (twice?), which has already been [implemented in this repository](https://github.com/LorenzNickel/java-fundamentals/blob/master/src/main/java/algorithms/sort/BubbleSort.java), **Matrixmultiplication**, which has been [implemented in this repository](https://github.com/LorenzNickel/java-fundamentals/blob/master/src/main/java/datastructures/math/Matrix.java#L150) and **Stringreversal**.

Please try to have a look if a feature has already been implemented because these won't be added a second time to this repo. Anyway, as you also implemented something new with **Stringreversal**, I'll leave this PR open for now.

If you want to continue with your PR, please remove the other files as they won't be merged into this repository.
Also make sure to place the file in the correct package, write junit tests, don't create a main-function and don't rely on scanners and stdout for your implementation. Please have a look at [this comment](https://github.com/LorenzNickel/java-fundamentals/pull/23#issuecomment-707027951) for more information on how to structure your PR.

Feel free to continue with this PR or close it and create a new one if you want.

**Comment by Pandz18** [comment]
hey Lorenz ,
I apologise for the two bubble programs as I thought it wasn't in my PR , also how do I open more than one PR and how do I see other programs ?

**Comment by LorenzNickel** [comment]
Hey @Pandz18,

other programs are listed in the [src folder](https://github.com/LorenzNickel/java-fundamentals/tree/master/src/main/java). There a several options on how to create another PR:

1. If you want to delete this PR and start all over, probably it's most easy to just delete your forked repository entirely and do the same process you did to create this PR.

2. The other option to create a second PR in parallel would be to create a new branch in your repository and create a PR from this other branch to this repository.

This resource might be helpful to you, make sure to have a look at it and also checkout the linked articles: [Proposing changes to your work with pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests)

**Comment by Pandz18** [comment]
Thank you so much will do

**Pull request closed without merging**
