### PR TITLE
Added Selection sort

### PR DESCRIPTION
**Pull request by AtharvaKamble**
Even though very similar to a Bubble Sort, I feel like Selection Sort needs to be in this.

### CODE REVIEW

**Comment by LorenzNickel** [comment]
Hey thanks for your contribution 🥇 

Seems like you have some checkstyle violations which cause the build to fail:

```
[ERROR] /home/travis/build/LorenzNickel/java-fundamentals/src/main/java/algorithms/sort/SelectionSort.java:24:49: WhitespaceAround: '{' is not preceded with whitespace. [WhitespaceAround]
[ERROR] /home/travis/build/LorenzNickel/java-fundamentals/src/main/java/algorithms/sort/SelectionSort.java:26: 'if' construct must use '{}'s. [NeedBraces]
```

Please try to fix them by applying the [style guide of this repository](https://github.com/LorenzNickel/java-fundamentals/blob/master/docs/CONTRIBUTING.md#style-guide). If you have any further questions let me know.

**Comment by LorenzNickel** [comment]
You can also just compile the project locally and the checkstyle tests will be executed locally to debug this. Let me know if you need further help 😄

**Comment by AtharvaKamble** [comment]
Wow finally Travis CI approved (they were really silly mistakes but at least now I know : D, haven't worked with automation bots), extremely sorry for making a load of commits 😄

**Comment by LorenzNickel** [comment]
Thanks for fixing the code style. Could you please remove the .idea/jarRepositories.xml file from this PR, then I'll be happy to provide feedback.

**Pull request merged**
