### PR TITLE
Shell Sort added

### PR DESCRIPTION
**Pull request by AtharvaKamble**
Shell sort is added to algorithms section

### CODE REVIEW

**Comment by LorenzNickel** [comment]
Hey @AtharvaKamble,

thanks for this new contribution 🏅

Would you mind also adding tests for arrays with different sizes, especially an empty array and an array with length 1 and maybe also 2? Also as your method is implemented in a generic way, could you also add a test with another type than `Short` implementing `Comparable` (e.g. `String`)?

**Comment by AtharvaKamble** [comment]
Yes definitely. I will ping back making the additions asap.

**Comment by AtharvaKamble** [comment]
Hello @LorenzNickel 
I have made the changes, if any more changes/additions feel free to ask. Hope the codecov errors are not causing any problems in the PR.

**Comment by LorenzNickel** [comment]
Could you also add tests with arrays of length 0, 1 and 2? For an array with the length 2 please include one array which is already sorted and one which is not (so that you have 4 additional tests).

**Comment by AtharvaKamble** [comment]
My bad @LorenzNickel I wrote the test cases in main file, but didn't write JUnit test cases for them in the test suite :sweat_smile: Hope this is what you are looking for, if not feel free to ask

**Comment by AtharvaKamble** [comment]
Hey @LorenzNickel extremely sorry for disturbing, but was wondering if you could add the `hacktoberfest-accepted` for my PRs??

**Comment by LorenzNickel** [comment]
Hm afaik the tag is not needed as the repository has the `hacktoberfest` tag. You should be able to see the PR on https://hacktoberfest.digitalocean.com/profile with status `In Review: Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days.`.

The [rules](https://hacktoberfest.digitalocean.com/faq) state about this:
`Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labeled as hacktoberfest-accepted. Additionally, any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.`

So the PR already should count as this repo has the relevant tag and the PR has been merged.

Let me know if you have any more questions.

**Comment by AtharvaKamble** [comment]
Yes this PR has been counted for the countdown of Hacktoberfest PRs. Thanks a lot. :+1: (I thought only the `hacktiberfest-accepted` tags are valid :sweat_smile:)

**Pull request merged**
