### PR TITLE
Adding JumpSearch file

### PR DESCRIPTION
**Pull request by jhanna60**

### CODE REVIEW

**Comment by jhanna60** [comment]
@LorenzNickel perhaps you can help me with this one please, I've added a JumpSearch implementation and covered it with 100% test coverage. The codecov/project — 89.31% (+-0.41%) compared to 0a5c3ba is still coming up I've also tried to offset this by removing unecessary code in the other implementations but its still not liking it. Seems to have an issue with /java/problems/checkSubTree/impl/Recursive.java and java/problems/checkSubTree/resources/TreeNode.java.

Thanks

**Comment by LorenzNickel** [comment]
Hey @jhanna60 thanks for tagging me.

Passing the codecoverage checks is not mandatory, don't worry about it too much, just make sure that you provide tests for added functionality where possible.

**Comment by jhanna60** [comment]
Ok thanks @LorenzNickel  in that case I've included 100% on my new Search - codecov/patch — 100.00% of diff hit (target 89.71%)

**Comment by LorenzNickel** [comment]
Could you create another commit to undo the deletions in the other files? Then I'll be happy to review your code.

**Comment by jhanna60** [comment]
Yes of course I'll do that now (they are unused methods and constructors) and they were bringing the code coverage results down.

**Comment by jhanna60** [comment]
@LorenzNickel that's the other deletions removed now and back to only my additions. Cheers

**Comment by LorenzNickel** [comment]
Would you think it makes sense to maybe somehow return (or maybe save as a state within the search object for the last search) how many "tries" it took to find the right element? Because this way you can only test if you found the correct element but not if the algorithm was actually implemented correctly (or to say it in other words if you have actually saved something compared to linear search). I'd say this something optional, but I wanted to suggest it. Let me know what you think and then I'll continue to review your changes.

**Comment by jhanna60** [comment]
@LorenzNickel interesting idea, I have added a quick state storage and retrieval so we can test that our algorithm is efficient. Let me know what you think

**Comment by LorenzNickel** [comment]
Thanks for your contribution, your willingness to adapt your code and your quick responses 🥇

**Pull request merged**
