### PR TITLE
Created HeapSort.java

### PR DESCRIPTION
**Pull request by iamvs-2002**

### CODE REVIEW

**Review by LorenzNickel — CHANGES_REQUESTED** [review]
Please make sure to provide tests for your changes :)

**Comment by iamvs-2002** [comment]
> Please make sure to provide tests for your changes :)

Do I need to add test cases in the comments? Or in a separate file?

**Comment by LorenzNickel** [comment]
Test cases should be place in the [Test](https://github.com/LorenzNickel/java-fundamentals/tree/master/src/test/java)-folder. You can have a look at existing tests to see how they should be implemented.

**Comment by iamvs-2002** [comment]
> Test cases should be place in the [Test](https://github.com/LorenzNickel/java-fundamentals/tree/master/src/test/java)-folder. You can have a look at existing tests to see how they should be implemented.

I have added the HeapSortTest.java file containing a test case.

**Pull request closed without merging**
